### ISSUE TITLE
Create release notes and release crate

### ISSUE THREAD

**Issue by no111u3** [stm32-rs/stm32g4xx-hal#67]
Crates doesn't look as WIP and ready to use (with some fixes, yeah)

@dotcypress could you create release for this crate?

**Comment by dotcypress** [comment]
Yep, I can do a release. Do we want to change any API before that? It would be harder to do breaking changes after release.

**Comment by no111u3** [comment]
After 0.1? Why not)

**Comment by dotcypress** [comment]
https://github.com/stm32-rs/stm32g4xx-hal/releases/tag/0.0.1
